### ISSUE TITLE
Theme does not work

### ISSUE THREAD

**Issue by mroberts1** [megrxu/hugo-water#1]
FYI, this theme doesn't work.

The problem appears to be that the two directories in the assets folder, which are requested in theme.scss, are remote directories in your repository. As a result, cloning the theme doesn't download the contents either of sass.mq or water.css

I tried manually installing both directories in the theme, but don't really understand how Hugo modules work. I was able to get the theme to load, but it wouldn't load any md files in /content/posts.

I don't know what the problem is but just wanted to let you know that the theme doesn't work.

**Comment by megrxu** [comment]
Glad you find this repo.

I have tested just now and find it works as expected. All you need is to init the submodules as well.

For example, to render the contents in directory `exampleSite`:
```bash
git clone https://github.com/megrxu/hugo-water.git && cd hugo-water
git submodule update --init --recursive
hugo server -s exampleSite
# then the hugo web server wil be available at http://localhost:{PORT}/hugo-water/
``` 

As for the issue that it wouldn't load your MD files in `/content/posts`, I suggest you follow the directory structure of `exampleSite`, or read the [documents](https://gohugo.io/documentation/) of hugo. Maybe you just need to specify the theme name in the config file.
